/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wxmylife_ccalljava_JNI */

#ifndef _Included_com_wxmylife_ccalljava_JNI
#define _Included_com_wxmylife_ccalljava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wxmylife_ccalljava_JNI
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wxmylife_ccalljava_JNI_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_wxmylife_ccalljava_JNI
 * Method:    callBackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wxmylife_ccalljava_JNI_callBackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_wxmylife_ccalljava_JNI
 * Method:    callBackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wxmylife_ccalljava_JNI_callBackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_wxmylife_ccalljava_JNI
 * Method:    callBackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wxmylife_ccalljava_JNI_callBackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
